### PR TITLE
drop unused constants, fix syntax error in filter

### LINKED ISSUE #111: Quotation marks in example values of the field `filter` cause a syntax error in Swagger UI
In Swagger UI, in the endpoint `/elements/count/ratio` quotation marks in the example value of the field `filter2` cause a syntax error.

We should also take a look at the example values in other endpoints.

### PR DESCRIPTION
**Pull request by tyrasd**
### Description
Fixes a syntax error in one of the default filter examples in swagger.

### Corresponding issue
Closes #111

### Checklist
- [x] My code follows the [code-style](https://github.com/GIScience/ohsome-api/blob/master/CONTRIBUTING.md#code-style) rules, and I have checked on the [static analyses](https://jenkins.ohsome.org/job/ohsome-api/view/change-requests/)
- ~~I have commented my code~~
- ~~I have written javadoc (required for public methods)~~
- ~~I have added sufficient unit and API tests~~
- [x] I have made corresponding changes to the [documentation](https://github.com/GIScience/ohsome-api/tree/master/docs)~~
- [x] I have updated the [CHANGELOG.md](https://github.com/GIScience/oshdb/blob/master/CHANGELOG.md)
- ~~I have adjusted the examples in the [check-ohsome-api](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/helpers/check-ohsome-api) script or [created an issue](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/helpers/check-ohsome-api/-/issues/new) in the corresponding repository. More Information [here](https://github.com/GIScience/ohsome-api/blob/master/CONTRIBUTING.md#check-examples).~~

### CODE REVIEW

File: src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/DefaultSwaggerParameters.java [hunk 1]
```diff
@@ -6,12 +6,10 @@
   public static final String BBOX = "8.625,49.3711,8.7334,49.4397";
   public static final String HIGHWAY_KEY = "highway";
   public static final String BUILDING_KEY = "building";
-  public static final String HOUSENUMBER_KEY = "addr:housenumber";
-  public static final String RESIDENTIAL_VALUE = "residential";
   public static final String TYPE_FILTER = "type:way";
   public static final String HIGHWAY_FILTER = "highway=residential";
   public static final String BUILDING_FILTER = "building=*";
-  public static final String HOUSENUMBER_FILTER = "type:node and \"addr:housenumber=*\"";
+  public static final String HOUSENUMBER_FILTER = "type:node and \"addr:housenumber\"=*";
```
Comment (FabiKo117) [inline src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/DefaultSwaggerParameters.java:12]: Would you recommend writing the key in that way using the quotation marks?

I think that tag here solely had those marks, because me (or whoever added that in the past) thought, that they are required for this specific key when using the filter parameter. Otherwise, we can just write it without the quotation marks and follow the conventions of the docs as you described it in the comment before.

Comment (tyrasd) [reply src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/DefaultSwaggerParameters.java:12]: > Would you recommend writing the key in that way using the quotation marks?

I would normally write it without the quote marks, but there's also nothing wrong with using them.

I left them in this PR because I thought it might be a hint for new users playing around in the swagger UI so find out that one can also define tag keys with `"`s.

**Review by FabiKo117 — APPROVED** [review]
