### PR TITLE
better handling of geojson parsing exceptions

### LINKED ISSUE #55: Improve error message on invalid AOI polygon input
More information in the error returned by the following POST request at /elements/geometry would help the user to debug the problem. The request contains an 'edge case of validity' as bpoly that our code cannot handle.

The error:
```
{'timestamp': '2020-09-29T07:23:30.664+0000', 'status': 500, 'error': 'Internal Server Error', 'message': 'found non-noded intersection between LINESTRING ( 5.820222602 50.508951342, 5.820318993 50.510568532 ) and LINESTRING ( 5.820319034 50.510568531, 5.820318993 50.510568532 ) [ (5.820318993, 50.510568532, NaN) ]', 'path': '/elements/geometry'}
```
I would expect an information like 'provided invalid input geometry' and an 'input error' rather than an internal server error.

This is the requests body (sorry, its rather long but it is the one at hand at the moment):
```
{'clipGeometry': False, 'properties': 'tags,metadata', 'filter': '(natural=cliff or natural=riverbank or landuse=pond or natural=bare_rock or natural=beach or natural=fell or natural=glacier or natural=grassland or natural=heath or natural=mud or natural=rock or highway=pedestrian or amenity=parking or leisure=common or leisure=garden or leisure=golf_course or leisure=marina or leisure=park or leisure=pitch or leisure=playground or leisure=sports_centre or leisure=stadium or leisure=track or landuse=farm or landuse=scrub or waterway=lock or tourism=zoo or natural=tidal or waterway=canal or landuse=greenhouse or tourism=camp_site or highway=raceway or landuse=raceway or highway=rest_area or aeroway=apron or aeroway=aerodrome or aeroway=runway or natural=marsh or landuse=allotments or landuse=basin or landuse=brownfield or landuse=cemetery or landuse=commercial or landuse=construction or landuse=farmland or landuse=logging or natural=desert or landuse=farmyard or landuse=forest or landuse=garages or landuse=grass or landuse=greenfield or landuse=greenhouse_horticulture or landuse=harbour or landuse=industrial or landuse=landfill or landuse=meadow or landuse=orchard or landuse=plant_nursery or landuse=port or landuse=quarry or landuse=railway or landuse=recreation_ground or landuse=reservoir or landuse=residential or landuse=retail or landuse=salt_pond or landuse=village_green or landuse=vineyard or natural=sand or natural=scree or natural=scrub or natural=water or natural=wetland or natural=wood or waterway=dock or waterway=riverbank) and geometry:polygon', 'time': '2017-10-15T10:40:09', 'bpolys': '{"type": "FeatureCollection", "features": [{"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[6.191243866, 49.731255792], [6.174618051, 49.731713066], [6.175321891, 49.742489836], [6.158691981, 49.742944899], [6.142061649, 49.743397579], [6.125430898, 49.743847874], [6.126124141, 49.754625131], [6.126817801, 49.765402361], [6.110179281, 49.765850611], [6.110869681, 49.776627983], [6.111560497, 49.787405328], [6.094914201, 49.78785153], [6.09560175, 49.798629017], [6.078951356, 49.799072999], [6.079635633, 49.809850628], [6.080320324, 49.820628229], [6.063662142, 49.821070156], [6.064343555, 49.831847898], [6.047681271, 49.832287601], [6.031018578, 49.832724911], [6.014355479, 49.833159829], [5.997691975, 49.833592355], [5.998359024, 49.844370731], [5.999026475, 49.85514908], [5.982355177, 49.855579539], [5.965683479, 49.856007603], [5.966343934, 49.866786251], [5.949668138, 49.867212082], [5.932991945, 49.867635517], [5.916315357, 49.868056555], [5.899638378, 49.868475198], [5.882961009, 49.868891444], [5.866283252, 49.869305294], [5.865644999, 49.85852569], [5.848970558, 49.858936987], [5.849605109, 49.869716747], [5.832926583, 49.870125803], [5.833557814, 49.880905692], [5.816875203, 49.881312505], [5.816247677, 49.870532463], [5.799568391, 49.870936725], [5.782888729, 49.87133859], [5.783508846, 49.882118939], [5.784129336, 49.892899262], [5.784750202, 49.903679559], [5.785371443, 49.91445983], [5.78599306, 49.925240076], [5.786615052, 49.936020296], [5.78723742, 49.946800489], [5.787860165, 49.957580657], [5.788483286, 49.9683608], [5.789106784, 49.979140916], [5.78973066, 49.989921006], [5.790354913, 50.000701071], [5.790979543, 50.01148111], [5.791604552, 50.022261122], [5.79222994, 50.03304111], [5.792855706, 50.043821071], [5.793481851, 50.054601006], [5.794108376, 50.065380915], [5.79473528, 50.076160799], [5.795362564, 50.086940657], [5.795990228, 50.097720488], [5.796618273, 50.108500294], [5.797246699, 50.119280074], [5.797875506, 50.130059828], [5.798504694, 50.140839557], [5.799134264, 50.151619259], [5.799764216, 50.162398935], [5.80039455, 50.173178586], [5.801025267, 50.18395821], [5.801656367, 50.194737809], [5.80228785, 50.205517382], [5.802919717, 50.216296929], [5.803551967, 50.227076449], [5.804184602, 50.237855944], [5.804817621, 50.248635414], [5.805451025, 50.259414857], [5.806084814, 50.270194274], [5.806718989, 50.280973665], [5.807353549, 50.29175303], [5.807988495, 50.30253237], [5.808623827, 50.313311683], [5.809259546, 50.324090971], [5.809895652, 50.334870232], [5.810532145, 50.345649468], [5.811169025, 50.356428677], [5.811806293, 50.367207861], [5.81244395, 50.377987019], [5.813081995, 50.38876615], [5.813720428, 50.399545256], [5.814359251, 50.410324336], [5.814998463, 50.421103389], [5.815638065, 50.431882417], [5.815830063, 50.435116119], [5.815830022, 50.43511612], [5.816054021, 50.43888812], [5.816278057, 50.442661419], [5.816374093, 50.444277902], [5.81647013, 50.445895114], [5.816694267, 50.449667104], [5.816918439, 50.453440395], [5.817014533, 50.455056873], [5.81711063, 50.456674082], [5.817334903, 50.460446063], [5.817559212, 50.464219344], [5.817655364, 50.465835819], [5.81775152, 50.467453024], [5.817975929, 50.471224996], [5.818200375, 50.474998268], [5.818296587, 50.476614739], [5.818392801, 50.47823194], [5.818617347, 50.482003902], [5.81884193, 50.485777166], [5.8189382, 50.487393633], [5.819034473, 50.48901083], [5.819259156, 50.492782783], [5.819483876, 50.496556038], [5.819580205, 50.4981725], [5.819676537, 50.499789694], [5.819901358, 50.503561638], [5.820126215, 50.507334883], [5.820126215, 50.507334883], [5.820222602, 50.508951342], [5.820318993, 50.510568532], [5.820319034, 50.510568531], [5.820318993, 50.510568532], [5.820543951, 50.514340466], [5.820768945, 50.518113703], [5.820768986, 50.518113702], [5.820961841, 50.521347344], [5.820961841, 50.521347344], [5.821605081, 50.53212613], [5.822248715, 50.54290489], [5.822892742, 50.553683623], [5.823537162, 50.564462331], [5.824181976, 50.575241013], [5.824827184, 50.586019669], [5.825472787, 50.596798299], [5.826118785, 50.607576902], [5.826765177, 50.61835548], [5.827411965, 50.629134031], [5.828059149, 50.639912557], [5.828706729, 50.650691056], [5.829354705, 50.66146953], [5.830003078, 50.672247977], [5.830651847, 50.683026398], [5.831301015, 50.693804793], [5.831950579, 50.704583163], [5.832600542, 50.715361506], [5.833250903, 50.726139823], [5.833901663, 50.736918113], [5.834552821, 50.747696378], [5.835204379, 50.758474617], [5.835856336, 50.769252829], [5.85285243, 50.768838027], [5.869848122, 50.76842075], [5.870508272, 50.779198619], [5.887507456, 50.778778709], [5.886843409, 50.768001], [5.903838289, 50.767578776], [5.903170756, 50.756801201], [5.920161334, 50.756376665], [5.92083276, 50.767154078], [5.937826819, 50.766726906], [5.954820464, 50.766297261], [5.971813693, 50.765865143], [5.988806502, 50.765430552], [6.00579889, 50.764993488], [6.022790855, 50.764553951], [6.022096076, 50.75377753], [6.039083724, 50.753335689], [6.056070944, 50.752891377], [6.055368815, 50.742115267], [6.054667115, 50.73133913], [6.071646131, 50.730892687], [6.088624715, 50.730443774], [6.105602865, 50.729992392], [6.122580577, 50.729538541], [6.121863778, 50.718763064], [6.13883717, 50.718306918], [6.13811693, 50.707531587], [6.137397131, 50.696756229], [6.154362326, 50.696297965], [6.153639093, 50.685522754], [6.170599971, 50.685062199], [6.16987331, 50.674287136], [6.169147093, 50.663512046], [6.186099786, 50.663049379], [6.185370147, 50.652274437], [6.184640954, 50.641499468], [6.201585471, 50.641034693], [6.21852954, 50.640567457], [6.235473159, 50.640097761], [6.234732829, 50.629323298], [6.251672134, 50.628851322], [6.252416325, 50.639625605], [6.269359035, 50.639150988], [6.268610985, 50.628376886], [6.285549378, 50.627899991], [6.284797928, 50.617126042], [6.267863392, 50.617602755], [6.267116255, 50.606828597], [6.266369575, 50.59605441], [6.24944229, 50.596528304], [6.248699917, 50.585753909], [6.231776029, 50.586225167], [6.231037958, 50.575450564], [6.214117468, 50.575919188], [6.213383694, 50.565144379], [6.196466602, 50.565610371], [6.19573712, 50.554835357], [6.195008084, 50.544060315], [6.211917489, 50.543594678], [6.211185058, 50.532819786], [6.210453074, 50.522044866], [6.227354355, 50.521577134], [6.226618982, 50.510802364], [6.243515979, 50.510332361], [6.260412526, 50.509859908], [6.277308619, 50.509385007], [6.294204257, 50.508907656], [6.311099436, 50.508427858], [6.327994156, 50.50794561], [6.327501468, 50.50094205], [6.327236293, 50.497171899], [6.344126671, 50.496687389], [6.361016634, 50.496200431], [6.36051927, 50.489197093], [6.360136808, 50.483810689], [6.359754468, 50.478423706], [6.359372239, 50.473037288], [6.358990133, 50.46765029], [6.358722768, 50.463880237], [6.375600741, 50.463391392], [6.375370483, 50.460159413], [6.392246842, 50.45966818], [6.391591291, 50.45051069], [6.391205833, 50.445123851], [6.390820486, 50.439737576], [6.390435262, 50.434350722], [6.390050149, 50.428964433], [6.389395729, 50.419807604], [6.372533488, 50.420298146], [6.372303693, 50.417066136], [6.371538175, 50.406292745], [6.370773122, 50.395519325], [6.370008536, 50.384745877], [6.369244414, 50.3739724], [6.368480758, 50.363198895], [6.385322879, 50.362709339], [6.402164532, 50.362217348], [6.401393744, 50.351444188], [6.418231132, 50.350949949], [6.417457017, 50.340176948], [6.416683374, 50.329403918], [6.415910201, 50.318630859], [6.399084192, 50.319124534], [6.398315277, 50.308351259], [6.38149259, 50.308842316], [6.380727928, 50.298068825], [6.363908562, 50.298557266], [6.347088734, 50.299043276], [6.347845821, 50.309817137], [6.331021746, 50.310300901], [6.314197212, 50.310782234], [6.313447699, 50.300008007], [6.296626498, 50.300486726], [6.295881227, 50.289712288], [6.295136409, 50.278937822], [6.294392043, 50.268163328], [6.293648129, 50.257388806], [6.276841606, 50.257864372], [6.260034632, 50.25833751], [6.243227212, 50.258808221], [6.242495083, 50.248033132], [6.225690995, 50.248501238], [6.208886466, 50.248966917], [6.208162333, 50.238191444], [6.20743864, 50.227415944], [6.190641221, 50.227878845], [6.189921739, 50.217103141], [6.189202694, 50.20632741], [6.205992571, 50.205864861], [6.205270194, 50.195089278], [6.204548256, 50.184313667], [6.203826755, 50.173538028], [6.187048174, 50.17400005], [6.170269157, 50.174459652], [6.169555616, 50.163683636], [6.152779928, 50.164140643], [6.152070578, 50.153364426], [6.168842508, 50.152907592], [6.168129831, 50.142131521], [6.167417587, 50.131355422], [6.150653169, 50.131811909], [6.149945109, 50.121035609], [6.149237477, 50.110259282], [6.148530275, 50.099482927], [6.1478235, 50.088706545], [6.131073649, 50.089159926], [6.130371047, 50.078383344], [6.129668869, 50.067606736], [6.128967117, 50.056830099], [6.145705744, 50.056377235], [6.14500068, 50.045600743], [6.144296042, 50.034824224], [6.143591831, 50.024047678], [6.160318829, 50.023592921], [6.159611314, 50.01281652], [6.158904227, 50.002040091], [6.158197568, 49.991263635], [6.174912956, 49.99080699], [6.174203001, 49.98003068], [6.190914237, 49.979571805], [6.190200992, 49.968795641], [6.206908077, 49.968334536], [6.206191545, 49.95755852], [6.222894479, 49.957095188], [6.239596979, 49.956629455], [6.238873451, 49.945853763], [6.238150359, 49.935078044], [6.237427705, 49.924302296], [6.236705487, 49.913526521], [6.235983704, 49.902750718], [6.252667218, 49.90228347], [6.251942168, 49.891507817], [6.268621541, 49.89103835], [6.267893229, 49.880262846], [6.284568462, 49.879791163], [6.301243253, 49.879317084], [6.3179176, 49.87884061], [6.317178635, 49.868065618], [6.333848839, 49.867586932], [6.333106624, 49.856812093], [6.349772686, 49.856331195], [6.366438298, 49.855847905], [6.383103458, 49.855362223], [6.382350616, 49.844587905], [6.399011631, 49.844100016], [6.398255554, 49.833325854], [6.397499933, 49.822551664], [6.414153117, 49.822061756], [6.430805843, 49.821569458], [6.447458109, 49.821074771], [6.464109914, 49.820577695], [6.464880277, 49.831351137], [6.481535302, 49.830851483], [6.480761254, 49.820078231], [6.497412127, 49.819576378], [6.514062532, 49.819072137], [6.530712465, 49.818565508], [6.529927838, 49.8077928], [6.546573617, 49.807283976], [6.545785783, 49.796511431], [6.529143683, 49.797020062], [6.52836, 49.786247296], [6.52757679, 49.7754745], [6.526794051, 49.764701675], [6.526011783, 49.75392882], [6.509383906, 49.754434299], [6.508605777, 49.743661224], [6.507828117, 49.73288812], [6.524448661, 49.732383024], [6.523667805, 49.721610082], [6.522887419, 49.710837111], [6.506274201, 49.711341825], [6.505497944, 49.700568634], [6.488887918, 49.701070778], [6.488115786, 49.690297367], [6.471508954, 49.690796944], [6.470740941, 49.680023315], [6.454137304, 49.680520326], [6.453373407, 49.669746481], [6.45260997, 49.658972606], [6.451846991, 49.648198703], [6.451084471, 49.637424771], [6.434494978, 49.637918656], [6.433736562, 49.627144508], [6.432978602, 49.616370332], [6.416395943, 49.616861472], [6.415642079, 49.606087081], [6.414888669, 49.595312661], [6.398312838, 49.595801059], [6.397563518, 49.585026426], [6.396814647, 49.574251764], [6.38024564, 49.574737425], [6.379500852, 49.563962551], [6.396066226, 49.563477074], [6.395318254, 49.552702356], [6.39457073, 49.541927609], [6.378012618, 49.542412718], [6.377269171, 49.531637759], [6.360714239, 49.532120319], [6.359974863, 49.521345149], [6.343423114, 49.521825163], [6.326870923, 49.522302812], [6.327603047, 49.533078344], [6.328335611, 49.543853848], [6.329068615, 49.554629325], [6.3125051, 49.555105149], [6.313234911, 49.565880777], [6.296667324, 49.566354413], [6.297393938, 49.577130193], [6.298120989, 49.587905944], [6.298848476, 49.598681667], [6.28226954, 49.59915347], [6.265690168, 49.599622902], [6.266410808, 49.610398953], [6.249827361, 49.610866191], [6.233243483, 49.611331056], [6.216659176, 49.611793548], [6.200074442, 49.612253667], [6.183489284, 49.612711413], [6.166903704, 49.613166787], [6.167602901, 49.623943858], [6.151013253, 49.62439703], [6.151709222, 49.635174246], [6.152405609, 49.645951434], [6.135808242, 49.646402573], [6.136501394, 49.657179905], [6.137194963, 49.66795721], [6.15379964, 49.66750573], [6.154497284, 49.678282836], [6.1711052, 49.677828806], [6.171806925, 49.688605713], [6.188418078, 49.688149131], [6.189123888, 49.698925837], [6.205738278, 49.698466702], [6.206448176, 49.709243207], [6.207158502, 49.720019684], [6.223779795, 49.719557819], [6.224494216, 49.730334094], [6.207869255, 49.730796134], [6.208580436, 49.741572556], [6.191951377, 49.742032388], [6.191243866, 49.731255792]], [[5.956207606, 50.517989226], [5.973111501, 50.517558428], [5.990014982, 50.517125178], [6.006918047, 50.516689477], [6.020439428, 50.516338975], [6.006918047, 50.516689477], [5.990014982, 50.517125178], [5.973111501, 50.517558428], [5.956207606, 50.517989226], [5.939512139, 50.518412281], [5.956207606, 50.517989226]], [[5.956207606, 50.517989226], [5.956005538, 50.514755968], [5.956005538, 50.514755968], [5.956207606, 50.517989226]], [[6.104332546, 50.453138259], [6.104332546, 50.453138259], [6.104332546, 50.453138259], [6.104332546, 50.453138259]], [[6.091215776, 50.511241352], [6.091215776, 50.511241352], [6.091427051, 50.514474208], [6.091427051, 50.514474208], [6.091215776, 50.511241352]], [[5.843505076, 50.520798271], [5.854775684, 50.520522528], [5.871682011, 50.520106441], [5.854775684, 50.520522528], [5.843505076, 50.520798271]]]}}]}'}
```

### PR DESCRIPTION
**Pull request by FabiKo117**
### Description
catching geojson parsing exception to give a proper 400 - BadRequestException
fix of not properly working GetControllerTest class in case no port1 parameter was given

### Corresponding issue
Closes #55

### Checklist
- [x] My code follows the [code-style](https://github.com/GIScience/ohsome-api/blob/master/CONTRIBUTING.md#code-style) rules, and I have checked on the [static analyses](https://jenkins.ohsome.org/job/ohsome-api/view/change-requests/)
~I have commented my code~
~I have written javadoc (required for public methods)~
- [x] I have added sufficient unit and API tests
~I have made corresponding changes to the [documentation](https://github.com/GIScience/ohsome-api/tree/master/docs)~
- [x] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-api/blob/master/CHANGELOG.md)
~I have adjusted the examples in the [check-ohsome-api](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/helpers/check-ohsome-api) script or [created an issue](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/helpers/check-ohsome-api/-/issues/new) in the corresponding repository. More Information [here](https://github.com/GIScience/ohsome-api/blob/master/CONTRIBUTING.md#check-examples).~

### CODE REVIEW

**Comment by tyrasd** [comment]
> catching geojson parsing exception to give a proper 400 - BadRequestException

currently, there already is a 400 error code returned if the bpolys parameter is invalid for a count request:

image

Does this fix only affect some endpoints and not others? Or just special cases of (geo)json parsing errors?

>  fix of not properly working GetControllerTest class in case no port1 parameter was given

Are these two independent bugfixes combined in one PR, or is this somehow related to the fix for the geojson parsing? It would be fine either way, just asking to understand.

File: src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java [hunk 1]
```diff
@@ -46,7 +46,9 @@ public static void applicationMainStartup() {
   /** Stops this application context. */
   @AfterClass
   public static void applicationMainShutdown() {
-    SpringApplication.exit(Application.getApplicationContext(), () -> 0);
+    if (null != Application.getApplicationContext()) {
```
Comment (tyrasd) [inline src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java:49]: it's a bit unconventional to reverse the condition structure from the "typical order" (a [yoda condition](https://en.wikipedia.org/wiki/Yoda_conditions)). did you have a specific reason for it in this occasion?

File: CHANGELOG.md [hunk 2]
```diff
@@ -3,10 +3,21 @@ Changelog
...
+* properly skip GetControllerTest class if no port1 parameter is set ([#164])
+
+[#55]: https://github.com/GIScience/ohsome-api/issues/55
+[#164]: https://github.com/GIScience/ohsome-api/pull/164
+
 
 ## 1.4.1
 
-* ugrade OSHDB to version [OSHDB#0.6.4], fixes thw following two bugs:
+* upgrade OSHDB to version [OSHDB#0.6.4], fixes the following two bugs:
```
Comment (tyrasd) [inline CHANGELOG.md:20]: merci <3

**Review by tyrasd — CHANGES_REQUESTED** [review]
This doesn't fix all null pointer dereferencing. Try this:

```json
{
  "type": "FeatureCollection"
}
```

Even after applying this PR I still get:

```
{
  "timestamp" : "2021-03-25T11:23:28.923+0000",
  "status" : 500,
  "error" : "Internal Server Error",
  "message" : "No message available",
  "path" : "/elements/count"
}
```


<hr>

also, for an empty feature collection (`{"type": "FeatureCollection", "features": []}`), the error code could be improved. Currently, it falsely states that the boundary does not lie withing the covered area:

```json
{
  "timestamp": "2021-03-25T11:20:29.676167",
  "status": 404,
  "message": "The provided boundary parameter does not lie completely within the underlying data-extract polygon.",
  "requestUrl": "https://api.ohsome.org/v1/elements/count?bpolys=%7B%20%20%20%22type%22%3A%20%22FeatureCollection%22%2C%20%20%20%22features%22%3A%20%5B%5D%20%7D&filter=type%3Away%20and%20natural%3D*&format=json&time=2014-01-01%2F2017-01-01%2FP1Y"
}
```

**Comment by tyrasd** [comment]
> fix of not properly working GetControllerTest class in case no port1 parameter was given

Is silently skipping of tests really the best approach? I mean tests can be skipped on purpose by adding `-DskipTests`. So if a user wants to execute the tests but forgets to provide all necessary settings (i.e. `port1`), the tests would not be executed, and no fail/error code be returned? IMHO that's not a good implementation. Or do I understand this incorrectly?

**Comment by tyrasd** [comment]
> Even after applying this PR I still get a NullPointerException at `GeometryBuilder.createGeometryFromGeoJson(GeometryBuilder.java:221)`:

btw, the actual line of code is `src/lombok/…/GeometryBuilder.java#L237` https://github.com/GIScience/ohsome-api/blob/68d94847b0319b80872feca5717dee0177a46d7f/src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java#L237. Sadly because of lombok (#57), the reported code lines in error messages don't align with our sources anymore. :cry:

**Comment by FabiKo117** [comment]
> > catching geojson parsing exception to give a proper 400 - BadRequestException
> 
> currently, there already is a 400 error code returned if the bpolys parameter is invalid for a count request:
> 
> image
> 
> Does this fix only affect some endpoints and not others? Or just special cases of (geo)json parsing errors?
> 
> > fix of not properly working GetControllerTest class in case no port1 parameter was given
> 
> Are these two independent bugfixes combined in one PR, or is this somehow related to the fix for the geojson parsing? It would be fine either way, just asking to understand.

It's a fix for the given example of @SlowMo24 in https://github.com/GIScience/ohsome-api/issues/55, which was before not caught and just returned an error message that was not helpful.

**Comment by tyrasd** [comment]
> It's a fix for the given example of @SlowMo24 in #55, which was before not caught and just returned an error message that was not helpful.

I understood that. However it would be nice to summarize what _exactly_ was fixed here in this PR.

File: src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java (hunk 1 above)
Comment (FabiKo117) [reply src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java:49]: I have just copied this if statement over from the other ControllerTest classes, as it was missing here. According to git-blame, you were actually implementing the statement in that way, or at least associated with the commit here:
https://github.com/GIScience/ohsome-api/commit/0b6c890e50294255d85532cbe37b1ae49488975f :P

Anyway, I did not think of any specific reasoning to write it in that order back then, if it was me. I just know that it can make sense to use it for string comparisons to avoid a potential nullpointer exception.

Comment (tyrasd) [reply src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java:49]: lol :rofl: 

> I just know that it can make sense to use it for string comparisons to avoid a potential nullpointer exception.

You mean when using `equals`, as in `"expected".equals(potenitallyNullStringVariable)`? yes, then it actually can make sense to reverse it.

**Comment by FabiKo117** [comment]
> also, for an empty feature collection ({"type": "FeatureCollection", "features": []}), the error code could be improved. Currently, it falsely states that the boundary does not lie withing the covered area:

I disagree here. The statement `The provided boundary parameter does not lie completely within the underlying data-extract polygon.` is also true if a GeoJSON containing no features is given. In a similar case, if no boundary parameter at all is given, it already returns a respective message. If we start to make very specific exception message for more and more use-cases, we will get old while doing that :D

> This doesn't fix all null pointer dereferencing. Try this:

It does not say anywhere that this branch fixes every possible GeoJSON parsing exception. Of course we can make this functionality more robust within this branch.

> Is silently skipping of tests really the best approach?

This approach with executing the tests when the required command line parameters are given has already been discussed in the past as far as I know. You get the message in the commandline stating e.g. `Tests run: 65, Failures: 0, Errors: 0, Skipped: 2` when you only defined one of the `port` parameters (in this case `port_data`). The `inputprocessing` tests are always executed, unless `-DskipTests` or `Djunit=no` is set. It should be sufficiently described here: https://github.com/GIScience/ohsome-api#testing

File: src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java (hunk 1 above)
Comment (FabiKo117) [reply src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java:49]: Yeah exactly. So you want to point out that it does not make sense here and would be better in `non-yoda` ordering? We can change that then yes, here and in the other test classes.

**Comment by tyrasd** [comment]
> > also, for an empty feature collection ({"type": "FeatureCollection", "features": []}), the error code could be improved. Currently, it falsely states that the boundary does not lie withing the covered area:
> 
> I disagree here. The statement `The provided boundary parameter does not lie completely within the underlying data-extract polygon.` is also true if a GeoJSON containing no features is given. In a similar case, if no boundary parameter at all is given, it already returns a respective message. If we start to make very specific exception message for more and more use-cases, we will get old while doing that :D

Well, this depends on how you handle empty collections in general. One commonly found approach is the so called [_vacuous truth_](https://en.wikipedia.org/wiki/Vacuous_truth), which would assign the answer `true` to the question whether an empty feature collection lies within a polygon. Btw: also the JDK uses this convention (e.g. in [`Stream.allMatch`](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#allMatch-java.util.function.Predicate-)).

I agree that it's definitely not something critical, and I can also live with the status quo, but IMHO it would be nicer to show the same or a similar error message to `NO_BOUNDARY` when an empty feature collection is encountered.

**Comment by tyrasd** [comment]
> > This doesn't fix all null pointer dereferencing. Try this:
> 
> It does not say anywhere that this branch fixes every possible GeoJSON parsing exception. Of course we can make this functionality more robust within this branch.

But I (the reviewer of this PR) say so. :stuck_out_tongue_closed_eyes:

File: src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java (hunk 1 above)
Comment (tyrasd) [reply src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java:49]: I'd say it's marginally better to change to the conventional order in all 3(?) test classes, if that's ok for you.

**Comment by FabiKo117** [comment]
Hm ok.. viewing it through this vacuous truth statement, the currently returned error message would actually not be fitting.

Still the question is how specific we want to be with our exception messages and on how much `"common sense"` of the user we can rely on. Because also with the currently returned exception message, it should be clear that something with the given boundary parameter is wrong.

> But I (the reviewer of this PR) say so.

:D Yeah that's why I said we can potentially fix more stuff within this branch. I'll put it back to WIP then to adress the discussed stuff and check for potential further parsing issues that might arise. Initially I just thought of fixing the linked issue, but yeah it would make sense to invest more time into that branch.

**Comment by tyrasd** [comment]
> Because also with the currently returned exception message, it should be clear that something with the given boundary parameter is wrong.

You are right. I also think that people should be clever enough to figure this out. Let's keep it as it is.

**Comment by FabiKo117** [comment]
I've moved more lines into the try-catch block and extended the error response message. Please have a look again @tyrasd.

File: src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java [hunk 3]
```diff
@@ -225,17 +225,22 @@ public void createGeometryFromMetadataGeoJson(String geoJson) {
...
+      throw new BadRequestException("Error in reading the provided GeoJSON. Please take a look at "
+          + "the documentation page for the bpolys parameter to see an example of a fitting "
+          + "GeoJSON input file.");
     }
     if (!"FeatureCollection".equals(root.getString("type"))) {
       throw new BadRequestException("The given GeoJSON has to be of the type 'FeatureCollection'.");
     }
-    JsonArray features = root.getJsonArray("features");
-    Object[] boundaryIds = new Object[features.size()];
-    GeoJsonObject[] geoJsonGeoms = new GeoJsonObject[features.size()];
```
[the remark this answers is not in the document]
Comment (tyrasd) [reply src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java:238]: PS: another option would be to use a json schema validator like https://github.com/everit-org/json-schema or https://github.com/networknt/json-schema-validator to check if the user input matches the official GeoJSON schema of a feature collection: https://geojson.org/schema/FeatureCollection.json

**Review by tyrasd — CHANGES_REQUESTED** [review]
Overall it looks good to me now, just two small-ish suggestions. See below.

File: src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (FabiKo117) [reply src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java:238]: I'd prefer your first suggestion here, since it does not increase the code complexity and still gives the necessary info to the user.

Regarding the schema validator: https://github.com/networknt/json-schema-validator actually looks nice as it also uses Jackson. It would add some processing overhead though, so the question is if it would be necessary, or if the current implementation is enough.

[the remark this answers is not in the document]
Comment (tyrasd) [reply src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java:238]: > I'd prefer your first suggestion here, since it does not increase the code complexity and still gives the necessary info to the user.

Seems reasonable to me as well :+1: We can keep the json validation option in mind for further improvements in the future.

**Review by tyrasd — DISMISSED** [review]

**Review by tyrasd — APPROVED** [review]
