### PR TITLE
Catch and throw new `BadRequestException` in cases of invalid `bpolys` boundary

### LINKED ISSUE #214: Wrong error in case of given boundary polygon with invalid coordinates
### Bug Description
The ohsome API returns an `Internal Server Error` and HTTP status code `500` in almost all cases of wrong given `bpolys` value (except for boundaries lying outside the underlying data-extract polygon).
The first tested request has obvious wrong coordinates with non-noded linestrings intersection. The response has the following message: `found non-noded intersection between LINESTRING ( 8.422694 49.47198, 8.426363 49.473583 ) and LINESTRING ( 8.426373 49.473593, 8.422684 49.47191 ) [ (8.42608150325082, 49.47346001300383, NaN) ]`

The second tested request has only one coordinates pair. The response has the following message: `Invalid number of points in LineString (found 1 - must be 0 or >= 2) `

### Expected Behaviour
In both cases, the thrown exception should be caught and a `BadRequestException` should be thrown. The ohsome API should return a `400` status code with an appropriate message.

### General Information
 - Version of the ohsome API: 1.5.0
 - API requested :`https://api.ohsome.org/v1`, local instance with an h2 file and connected to the cluster
 - Affected endpoint(s): tested on `/elements/count` but probably all
 - URL of your request: [request1](https://api.ohsome.org/v1/elements/count?bpolys=8.422684%2C49.471910%2C8.422694%2C49.471980%20%7C8.426363%2C49.473583%2C8.426373%2C49.473593%20%7C8.422684%2C49.471910%2C8.422694%2C49.471980&filter=type%3Away%20and%20natural%3D*&format=json&time=2014-01-01%2F2017-01-01%2FP1Y), [request2](https://api.ohsome.org/v1/elements/count?bpolys=8.65821%2C49.41129&filter=type%3Away%20and%20natural%3Dtree&format=json&time=2014-01-01%2F2017-01-01%2FP1Y)
 - Used HTTP method: GET
 - Utilized tool/library for the request: cURL, Swagger

### PR DESCRIPTION
**Pull request by bonaparten**
### Description
Catches and throws a new `BadRequestException` in cases of an invalid geometry given through the `bpolys` parameter.

### Corresponding issue
Closes #214 

### Checklist
- [x] My code follows the [code-style](https://github.com/GIScience/ohsome-api/blob/master/CONTRIBUTING.md#code-style) rules, and I have checked on the [static analyses](https://jenkins.ohsome.org/job/ohsome-api/view/change-requests/)
- [x] I have added sufficient unit and API tests
- [x] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-api/blob/master/CHANGELOG.md)

### CODE REVIEW

File: src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessor.java [hunk 1]
```diff
@@ -212,11 +211,13 @@ public InputProcessor(HttpServletRequest servletRequest, boolean isSnapshot, boo
       mapRed =
           mapRed.areaOfInterest(OSHDBGeometryBuilder.boundingBoxOf(boundary.getEnvelopeInternal()));
     } else {
-      mapRed = mapRed.areaOfInterest((Geometry & Polygonal) boundary);
+      try {
+        mapRed = mapRed.areaOfInterest((Geometry & Polygonal) boundary);
+      } catch (TopologyException e) {
+        throw new BadRequestException("Invalid geometry: " + e.getMessage());
```
Comment (tyrasd) [inline src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessor.java:217]: maybe this error message could be slightly more specific, e.g. that the invalid geometry was encountered in the boundary parameter. Also for consistency it could be stored in the `ExceptionMessages` alongside the other error messages, right?

File: src/test/java/org/heigit/ohsome/ohsomeapi/controller/PostControllerTest.java [hunk 2]
```diff
@@ -81,6 +81,38 @@ public void providedBpolysOutsideUnderlyingDataExtractPolygonTest() {
...
+    assertEquals(message, response.getBody().get("message").asText());
+  }
+
+  @Test
+  public void nonNodedLinestringsIntersectionTest() {
+    TestRestTemplate restTemplate = new TestRestTemplate();
+    MultiValueMap<String, String> map = new LinkedMultiValueMap<>();
+    String message = "Invalid geometry: found non-noded intersection between LINESTRING "
+        + "( 8.696384 49.401269, 8.674739 49.401869 ) and LINESTRING ( 8.681818 49.404774, "
+        + "8.695483 49.400794 ) [ (8.693585810865496, 49.401346565880374, NaN) ]";
```
Comment (tyrasd) [inline src/test/java/org/heigit/ohsome/ohsomeapi/controller/PostControllerTest.java:107]: I'm not sure if we really want to test the exact output of the error message (which comes from the JTS dependency), since this could change whenever we upgrade JTS for example. Wouldn't it suffice to check that the returned error message starts with `Invalid geometry:`, since that's the only part of the error message we control.

**Review by tyrasd — COMMENTED** [review]
thanks for the PR :+1: see two comments inline below

**Review by tyrasd — DISMISSED** [review]

**Review by tyrasd — APPROVED** [review]
